build:
  runs-on: ubuntu-latest
  needs: preflight
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Build with Maven
      run: mvn clean install
    - name: Run Tests
      run: mvn test
    - name: Generate Jacoco Report
      run: mvn jacoco:report
    - name: Upload Jacoco Report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
    - name: Upload Jacoco Report to FTP
      env:
        FTPHOST: ${{ secrets.FTPHOST }}
        FTPUSER: ${{ secrets.FTPUSER }}
        FTPPASS: ${{ secrets.FTPPASS }}
      run: |
        sudo apt-get install -y lftp
        lftp -u $FTPUSER,$FTPPASS $FTPHOST -e "
        mirror -R target/site/jacoco /A3Unifacs20241;
        quit"
    - name: SonarCloud Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=MatheusLobo_A3Unifacs20241 -Dsonar.organization=matheuslobo -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
