name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ main, develop, release ]

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate Commit Message
        run: |
          commit_message=$(git log -1 --pretty=format:"%s" HEAD)
          if [[ ! $commit_message =~ ((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*) ]]; then
            echo "commit is not valid: '$commit_message'"
            exit 1
          fi
      - name: Install Commitlint
        run: npm install -g @commitlint/cli
