name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'adopt'

      - uses: actions/setup-node@v2
        with:
          node-version: '20'

      - run: mvn package

      - run: npm install -g @commitlint/cli

      - id: commit_hash
        run: echo "MAIN_COMMIT_HASH=$(git rev-parse main)" >> $GITHUB_ENV

      - run: |
          commit_message=$(git log -1 --pretty=format:"%s" HEAD)
          if [[ ! $commit_message =~ ((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.*\))?!?: .*) ]]; then
            echo "commit is not valid: '$commit_message'"
            exit 1
          fi

      - run: echo "REPOSITORY_URL=https://github.com/MatheusLobo/A3Unifacs20241" >> $GITHUB_ENV

      - run: echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

      - run: npm ci

      - run: npm config -g set git-tag-version false

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        run: npx semantic-release

      - uses: actions/upload-artifact@v2
        with:
          name: gqs
          path: /target/gqs-1.0-SNAPSHOT.jar