name: Build with Maven

jobs:
  maven-build:
    runs-on: ubuntu-latest

    steps:
      - name: Build with Maven
        run: |
          mvn -B package -f gqs/pom.xml
          mvn -B test -f gqs/pom.xml
