name: Run Semantic Release

jobs:
  semantic-release:
    runs-on: ubuntu-latest

    steps:
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }} 
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
        run: npx semantic-release
