name: Setup Node.js Environment

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'
