name: Setup Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
